export type ShapeType =
  | 'square'
  | 'circle'
  | 'triangle'
  | 'pentagon'
  | 'hexagon'
  | 'polygon-7'
  | 'polygon-8'
  | 'polygon-9'
  | 'star-5'
  | 'star-10'
  | 'star-11'
  | 'star-12'
  | 'star-13'
  | 'star-15'
  | 'star-19'
  | 'star-20';
